name: Update CNAME

on:
  push:
    branches:
      - gh-pages
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  update-cname:
    runs-on: ubuntu-latest
    steps:
      - name: Clone, Echo, and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git clone --depth 1 --branch "gh-pages" "https://${GITHUB_TOKEN}@github.com/afbase/slavecodes_org.git"
          cd slavecodes_org
          echo "slavecodes.org" > CNAME
          git config --local user.email "afbase@users.noreply.github.com"
          git config --local user.name "clinton bowen"
          git add CNAME
          git commit -m "Update CNAME file" || echo "No changes to commit"
          git push