name: Update CNAME

on:
  push:
    branches:
      - gh-pages
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  update-cname:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create CNAME file
        run: echo "slavecodes.org" > CNAME

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CNAME
          git commit -m "Update CNAME file" || echo "No changes to commit"
          git push